/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 * <p/>
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 * <p/>
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 * <p/>
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.kernel;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import rapture.common.CallingContext;
import rapture.common.annotations.SampleCode;
import rapture.common.api.DocApi;

public class LegacyDocApiImplTest {

    DocApi api;

    @SampleCode(api = "doc")
    public void testGetDoc() {
        CallingContext ctx = ContextFactory.getKernelUser();
        String docUri = "document://myrepo/mydoc";

        // setup our json content
        String jsonContent = "{ \"key\" : \"value\" }";

        // put a document first
        assertEquals(docUri, api.putDoc(ctx, docUri, jsonContent));
        // now get the same document out
        assertEquals(jsonContent, api.getDoc(ctx, docUri));

        // attempt to get a document that does not exist, should return null
        assertNull(api.getDoc(ctx, "document://unknown/doesntexist"));
    }
}
