/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.repo.cassandra.key;

/**
 * This class contains a Cassandra key that's been normalized. This is to distinguish at compile time between a key that is normalized vs. one that is not
 *
 * @author bardhi
 * @since 3/10/15.
 */
public class NormalizedKey {
    private final String value;

    public NormalizedKey(String value) {
        this.value = value;
    }

    public String get() {
        return value;
    }

    public String toString() {
        return value;
    }
}
