/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.repo.cassandra.key;

import rapture.repo.cassandra.CassFolderHandler;

import java.util.LinkedList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

/**
 * An "external" path is the path seen by users of the app, without any partition key prefixes that we use internally when storing in Cassandra. This is
 * intended to receive regular strings and append those into a path
 *
 * @author bardhi
 * @since 3/10/15.
 */
public class PathBuilder {
    private final String root;
    private List<String> subPaths = new LinkedList<>();

    public PathBuilder(String prefix) {
        this.root = PathStripper.stripPrefix(prefix);
    }

    public PathBuilder subPath(String name) {
        subPaths.add(name);
        return this;
    }

    public String build() {
        String joined = StringUtils.join(subPaths, "/");
        if (CassFolderHandler.DOLLAR_ROOT.equals(root)) {
            return joined;
        } else {
            return root + "/" + joined;
        }
    }

}
