/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.repo.cassandra.key;

import rapture.repo.cassandra.CassFolderHandler;

import org.apache.commons.lang.StringUtils;

/**
 * @author bardhi
 * @since 3/10/15.
 */
public class PathStripper {
    public static String stripPrefix(String prefix) {
        prefix = StringUtils.trimToEmpty(prefix);
        prefix = StringUtils.stripEnd(prefix, "/");
        prefix = StringUtils.stripStart(prefix, "/");
        if (StringUtils.isBlank(prefix)) {
            prefix = CassFolderHandler.DOLLAR_ROOT;
        }
        return prefix;
    }
}
