/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package raptureint;

import static org.junit.Assert.fail;

import org.junit.Test;

import rapture.common.client.HttpLoginApi;
import rapture.common.client.HttpUserApi;
import rapture.common.client.SimpleCredentialsProvider;
import rapture.common.exception.RaptureException;
import rapture.common.model.RaptureUser;

public class HttpCheck {
    @Test
    public void testSimpleConnection() {
        String url = "http://localhost:8665/rapture";
        HttpLoginApi loginApi = new HttpLoginApi(url, new SimpleCredentialsProvider("rapture", "rapture"));
        try {
            loginApi.login();
            HttpUserApi userApi = new HttpUserApi(loginApi);
            userApi.setContext(loginApi.getContext());
            RaptureUser user = userApi.getWhoAmI(null);
            System.out.println("User is " + user.getUsername());
        } catch (RaptureException e) {
            fail(e.getMessage());
        }
    }
}
