/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package raptureint;

import org.junit.Ignore;
import org.junit.Test;

import rapture.common.exception.RaptureException;
import rapture.dsl.dparse.AbsoluteVersion;
import rapture.repo.RepoFactory;
import rapture.repo.Repository;

/**
 * Note not called test because this may take a while
 * 
 * @author moorala
 * 
 */
public class RepoPerformance {
    @Test @Ignore
    public void runPerformance() {
        Repository r = RepoFactory.getRepo("VREP { test = \"\"} using FILE { rootFolder=\"c:\\test\\\"}");
        for (int i = 0; i < 1000; i++) {
            try {
                r.addDocument("test/" + i, "{\"content\" : " + i + " }", "tester", "Test for " + i, false);
            } catch (RaptureException e) {
                e.printStackTrace();
            }
        }

        for (int i = 0; i < 1000; i++) {
            try {
                System.out.println(r.getDocument("test/" + i));
            } catch (RaptureException e) {
                e.printStackTrace();
            }
        }
    }
}
