package rapture.field.model;

/**
 * This will ultimately be autogenerated because it will be done through the API
 */
 
public class FieldDefinition {
    private String uri;
    private String description;
    private String validationScript; // if present, what script can validate that a passed in value is correct?
    private FieldType fieldType; // What type of field is this?
    private String fieldTypeExtra; // Depending on the field type this can reference other things. 
                                  // E.g. a fieldType of ARRAY or MAP has a structure/schema defined here
                                  
    public void setUri(String uri) {
        this.uri = uri;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public void setValidationScript(String validationScript) {
        this.validationScript = validationScript;
    }
    
    public void setFieldType(FieldType fieldType) {
        this.fieldType = fieldType;
    }
    
    public void setFieldTypeExtra(String fieldTypeExtra) {
        this.fieldTypeExtra = fieldTypeExtra;
    }
    
    public String getUri() {
        return uri;
    }
    
    public String getDescription() {
        return description;
    }
    
    public String getValidationScript() {
        return validationScript;
    }
    
    public FieldType getFieldType() {
        return fieldType;
    }
    
    public String getFieldTypeExtra() {
        return fieldTypeExtra;
    }
}