/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.ftp.common;

import java.util.List;

public interface Connection {

    boolean connectAndLogin();

    boolean isConnected();

    /**
     * Log off and terminate the connection, e.g. close the connection socket.
     * 
     * If there is a failure in the implementation of this method, it may or may
     * not be appropriate to throw an Exception. Throwing an exception will
     * cause the entire Workflow to end in error. If this is not appropriate,
     * take a look at {@link WarningHandler}, which can be used to log a
     * warning.
     */
    void logoffAndDisconnect();

    public boolean doActions(List<FTPRequest> requests);

    public boolean doAction(FTPRequest request);

    public List<String> listFiles(String path);

}
