/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.repo.cassandra;

import java.util.Map;

import org.apache.commons.lang.StringUtils;

import rapture.cassandra.CassandraConstants;

import com.google.common.base.Optional;

/**
 * @author bardhi
 * @since 3/10/15.
 */
public class ConfigParser {
    private static final Optional<String> ABSENT = Optional.absent();
    private final Map<String, String> config;
    private String keyspaceName;
    private String cfName;
    private Optional<String> pKeyPrefix;

    public ConfigParser(Map<String, String> config) {
        this.config = config;
    }

    public String getKeyspaceName() {
        return keyspaceName;
    }

    public void parse() {
        keyspaceName = config.get(CassandraConstants.KEYSPACECFG);

        cfName = config.get(CassandraConstants.CFCFG);

        if (StringUtils.isBlank(cfName)) {
            String authority = config.get(CassandraConstants.AUTHORITY);
            if (!StringUtils.isBlank(authority)) {
                int indexDot = authority.indexOf(".");
                if (indexDot != -1) {
                    cfName = authority.substring(0, indexDot);
                    if (authority.length() > indexDot + 1) {
                        pKeyPrefix = Optional.of(authority.substring(indexDot + 1, authority.length()));
                    } else {
                        pKeyPrefix = ABSENT;
                    }
                } else {
                    cfName = authority;
                    pKeyPrefix = ABSENT;
                }

            }
        } else {
            String tempPrefix = config.get(CassandraConstants.PARTITION_KEY_PREFIX);
            if (StringUtils.isBlank(tempPrefix)) {
                pKeyPrefix = ABSENT;
            } else {
                pKeyPrefix = Optional.of(tempPrefix);
            }
        }
    }

    public String getCfName() {
        return cfName;
    }

    public Optional<String> getpKeyPrefix() {
        return pKeyPrefix;
    }
}
