/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.plugin.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.io.File;
import java.io.IOException;

import org.junit.Test;

import rapture.common.PluginConfig;
import rapture.plugin.util.PluginUtils;

import com.google.common.io.Files;

public class PluginUtilsTest {

    @Test
    public void testGetPluginConfigFromZip() throws IOException {
        File fzip = TestHelper.createTempZipWithPluginTxt(Files.createTempDir(), "apluginzip.zip", "TestPlugin");
        PluginConfig config = new PluginUtils().getPluginConfigFromZip(fzip.getPath());
        assertNotNull(config);
        assertEquals("TestPlugin", config.getPlugin());
    }

}
