/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.repo.jdbc.context;

import java.util.ArrayList;
import java.util.List;

import net.sf.jsqlparser.schema.Table;

/**
 * Created by yanwang on 5/4/15.
 */
public class StatementContext {
    private StatementType StatementType;
    private List<Table> tables;

    public StatementContext(StatementType StatementType) {
        this.StatementType = StatementType;
        tables = new ArrayList<>();
    }

    public StatementType getStatementType() {
        return StatementType;
    }

    public List<Table> getTables() {
        return tables;
    }

    public void addTable(Table table) {
        tables.add(table);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("tables: ").append(tables).append("\n");
        return sb.toString();
    }
}
