/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.common.client;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;

import rapture.common.LocalHttpServerTests;

@Category(LocalHttpServerTests.class)
public class EventApiTest {

    protected static final SimpleCredentialsProvider CREDENTIALS_PROVIDER =
            new SimpleCredentialsProvider("rapture", "rapture");

    HttpEventApi event;
    
    @Before
    public void setup() {
        String host = "http://localhost:8665/rapture";
        HttpLoginApi login = new HttpLoginApi(host, CREDENTIALS_PROVIDER);
        login.login();
        event = new HttpEventApi(login);
    }
    
    @Test
    public void testDoesEventExist() {
        
        String goodURI = "event://idp.order/data/update";
        String badURI = "event://bonzo.dog/UrbanSpaceman";
        Assert.assertTrue(goodURI, event.eventExists(goodURI));
        Assert.assertFalse(badURI, event.eventExists(badURI));        
    }
}
