/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.common.client;

import java.util.List;

import org.junit.Test;

import rapture.common.model.RestFolderInfo;

public class RestClientTest {
    @Test
    public void testRestClient() {
        HttpLoginApi loginApi = new HttpLoginApi("http://localhost:8665/rapture", new SimpleCredentialsProvider("rapture", "rapture"));
        RestClient rc = new RestClient(loginApi, "http://localhost:8665/rapture");
        List<RestFolderInfo> res = rc.getRootFolderInfo();
        for (RestFolderInfo r : res) {
            System.out.println(r.getName());
            List<RestFolderInfo> inner = rc.getFolderInfo(r);
            for (RestFolderInfo i : inner) {
                if (i != null) {
                    System.out.println(" --- " + i.getName());
                }
            }
        }
    }
}
