/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package reflex.app.handler;

import reflex.DebugLevel;
import reflex.IReflexDebugHandler;

public class ReflexDebugHandler implements IReflexDebugHandler {

    @Override
    public void debugOut(int arg0, DebugLevel arg1, String arg2) {
    }

    @Override
    public void statementReached(int arg0, DebugLevel arg1, String arg2) {
        debugOut(arg0, arg1, arg2);
    }

    @Override
    public boolean hasCapability() {
        return true;
    }

}
