/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.postgres.connection.cache;

import rapture.repo.jdbc.TransactionAwareDataSource;
import rapture.repo.postgres.PostgresSanitizer;

/**
 * @author bardhi
 * @since 3/30/15.
 */
public class ConnectionInfo {
    private TransactionAwareDataSource dataSource;

    public PostgresSanitizer getSanitizer() {
        return sanitizer;
    }

    public void setSanitizer(PostgresSanitizer sanitizer) {
        this.sanitizer = sanitizer;
    }

    public TransactionAwareDataSource getDataSource() {
        return dataSource;
    }

    public void setDataSource(TransactionAwareDataSource dataSource) {
        this.dataSource = dataSource;
    }

    private PostgresSanitizer sanitizer;
}
