/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.cassandra;

/**
 * Constants related to the configuration of Cassandra
 *
 * @author dukenguyen
 */
public class CassandraConstants {

    public static final String AUTHORITY = "authority";
    /**
     * configuration constant used to configure the keyspace to use for
     * cassandra in RaptureCASSANDRA.cfg
     */
    public static String KEYSPACECFG = "keyspace";

    /*
     * used to configure the column family to use for cassandra in
     * RaptureCASSANDRA.cfg
     */
    public static String CFCFG = "cf";

    /**
     * Used to configure the row prefix, if any
     */
    public static String PARTITION_KEY_PREFIX = "partitionKeyPrefix";

    /*
     * used to configure the read consistency level in Cassandra, default is ONE
     * if unspecified
     */
    public static final String READ_CONSISTENCY = "readConsistency";

    /*
     * used to configure the write consistency level in Cassandra, default is
     * ONE if unspecified
     */
    public static final String WRITE_CONSISTENCY = "writeConsistency";

    public static final String OVERFLOWLIMITCFG = "overflowLimit";

    public static final int DEFAULT_OVERFLOW = 1000000;

}
