/**
 * Copyright (C) 2011-2015 Incapture Technologies LLC
 *
 * This is an autogenerated license statement. When copyright notices appear below
 * this one that copyright supercedes this statement.
 *
 * Unless required by applicable law or agreed to in writing, software is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied.
 *
 * Unless explicit permission obtained in writing this software cannot be distributed.
 */
package rapture.server;

import java.util.HashMap;
import java.util.Map;

import org.apache.log4j.Logger;

import rapture.config.ConfigLoader;
import rapture.apiutil.StatusHelper;
import rapture.app.RaptureAppService;
import rapture.common.exception.ExceptionToString;
import rapture.common.exception.RaptureException;
import rapture.kernel.ContextFactory;
import rapture.kernel.Kernel;
import rapture.kernel.schedule.ScheduleManager;
import rapture.util.IDGenerator;

/**
 * This is the entry point for the RaptureServer
 *
 * @author alan
 */
public final class ScheduleServer {

    private ScheduleServer() {
    }

    private static Logger log = Logger.getLogger(ScheduleServer.class);

    /**
     * @param args
     */
    public static void main(String[] args) {
        try {
            RaptureAppService.setupApp("ScheduleServer");

            try {
                Map<String, String> templates = new HashMap<String, String>();
                templates.put("STD", ConfigLoader.getConf().StandardTemplate);
                Kernel.initBootstrap(templates, ScheduleServer.class, false);
                Kernel.getKernel().setAppStyle("schedule");
                Kernel.getKernel().setAppId(IDGenerator.getUUID());
            } catch (RaptureException e1) {
                log.error("Failed to start Rapture with " + ExceptionToString.format(e1));
                System.exit(-1);
            }

        } catch (RaptureException e) {
            log.error("Error when running Rapture - " + ExceptionToString.format(e));
        }

        Map<String, Object> cap = new HashMap<String, Object>();
        StatusHelper.setStatusAndCapability(ContextFactory.getKernelUser(), "RUNNING", cap, Kernel.getRunner());
        StatusHelper.startStatusUpdating(ContextFactory.getKernelUser(), Kernel.getRunner());

        // We will call the schedule manager periodically (after locking)
        while (true) {
            try {
                Thread.sleep(1000);
                try {
                    ScheduleManager.manageJobExecStatus();
                } catch (Exception e) {
                    log.error(String.format("Got exception %s when running a task, the show goes on. stack: %s", e.getMessage(), ExceptionToString.format(e)));
                }
            } catch (InterruptedException e) {
                log.error("Error while sleeping on main thread");
                System.exit(-1);
            }
        }
    }
}
